pipeline {
    agent any

    environment {
        DOCKER_IMAGE = '1231859/springboot-app:${BUILD_NUMBER}'
    }

    stages {
        stage('Checkout') {
            steps {
                echo 'Checking out code from the repository'
                git branch: 'main', url: 'https://github.com/simao-campos87/devops-23-24-JPE-1231859.git'
            }
        }
        stage('Assemble') {
            steps {
                echo 'Assembling application...'
                dir('ca2/part2/react-and-spring-data-rest-basic') {
                    sh 'chmod +x ./gradlew'
                    sh './gradlew clean assemble'
                }
            }
        }
        stage('Test') {
            steps {
                echo 'Running tests...'
                dir('ca2/part2/react-and-spring-data-rest-basic') {
                    sh './gradlew test'
                    junit 'build/test-results/test/*.xml'
                }
            }
        }
        stage('Javadoc') {
            steps {
                echo 'Generating Javadoc...'
                dir('ca2/part2/react-and-spring-data-rest-basic') {
                    sh './gradlew javadoc'
                    publishHTML(target: [
                        allowMissing: false,
                        alwaysLinkToLastBuild: true,
                        keepAll: true,
                        reportDir: 'build/docs/javadoc',
                        reportFiles: 'index.html',
                        reportName: 'Javadoc'
                    ])
                }
            }
        }
        stage('Archive') {
            steps {
                echo 'Archiving artifacts...'
                dir('ca2/part2/react-and-spring-data-rest-basic') {
                    archiveArtifacts 'build/libs/*.jar'
                }
            }
        }
        stage('Publish Image') {
            steps {
                echo 'Building and pushing Docker image...'
                dir('ca2/part2/react-and-spring-data-rest-basic') {
                    script {
                        // Building the Docker image with a tag that includes the build number
                        def appImage = docker.build("1231859/springboot-app:${env.BUILD_NUMBER}")
                        docker.withRegistry('https://registry.hub.docker.com', 'docker-hub-credentials') {
                            // Pushing the image using the tagged image name
                            appImage.push()
                            echo "Building image with tag: 1231859/springboot-app:${env.BUILD_NUMBER}"
                        }
                    }
                }
            }
        }
    }
}
